function [h,J] = transform_cart_to_sph
% --- transform_cart_to_pol() ---------------------------------------------
% Transform from Cartesian (3D) to spherical coordinates. Includes Jacobian.
%
% 2023-10-30 Robin Forsling

h = @(x) [  sqrt(x(1)^2+x(2)^2+x(3)^2); ...     
            atan2(x(2), x(1)) ; ...   
            atan2(x(3), sqrt(x(1)^2 + x(2)^2)) ]; 
        
J = @(x) [  x(1)/sqrt(x(1)^2+x(2)^2+x(3)^2) ...      
            x(2)/sqrt(x(1)^2+x(2)^2+x(3)^2) ...  
            x(3)/sqrt(x(1)^2+x(2)^2+x(3)^2) ...
            ; ...
            -x(2)/(x(1)^2+x(2)^2) ...                                   
            x(1)/(x(1)^2+x(2)^2) ...                                    
            0 ...                                                                   
            ; ...                                                     
            -x(1)*x(3)/(sqrt(x(1)^2+x(2)^2)*(x(1)^2+x(2)^2+x(3)^2)) ... 
            -x(2)*x(3)/(sqrt(x(1)^2+x(2)^2)*(x(1)^2+x(2)^2+x(3)^2)) ...  
            sqrt(x(1)^2+x(2)^2)/(x(1)^2+x(2)^2+x(3)^2) ];               